config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'tasks#index'
  resources :tasks

  get 'signup'  => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  scope :todo, -> { where(completed: false) }
  scope :completed, -> { where(completed: true) }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user, only: [:index, :show]

  helper_method :resource_task

  def index
    @tasks = current_user.tasks
  end

  def show
  end

  def new
  end

  def create
    @task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task created!' }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if resource_task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Update completed' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    resource_task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: 'Task destroyed!' }
    end
  end

  protected

  def resource_task
    @task = params[:id].present? ? Task.find(params[:id]) : Task.new
  end

  def task_params
    params.require(:task).permit(:title, :completed, :due_date, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/singup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <ul>
        <li><%= current_user.email %></li>
        <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to 'Login', 'login' %></a></li>
        <li><%= link_to 'Signup', 'signup' %></a></li>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.slim
= form_with model: resource_task, local: true do |f|
  div
    = f.label :title
    = f.text_field :title, disabled: readonly
  br
  div
    = f.label :description
    = f.text_field :description, disabled: readonly
  br
  div
    = f.label :completed
    = f.check_box :completed, disabled: readonly
  br
  div
    = f.label :due_date
    = f.date_field :due_date, disabled: readonly

  br
  - unless readonly
    div
      = f.submit class: 'btn-submit'

app/views/tasks/_task.html.slim
= link_to task do
  = task.title
  - if task.due_date.present?
    = ": #{task.due_date.strftime('%m/%d/%Y')}"

app/views/tasks/edit.html.slim
h1
  = "Editing #{resource_task.title}"

= link_to  'Back', tasks_path

= render 'form', readonly: false

app/views/tasks/index.html.slim
h1 class="tasks-header"
  | Tasks

= link_to  'create task', new_task_path, class: 'btn-create'
br
br

| TODO
table
  - @tasks.todo.each do |task|
    tr
      td
        = render 'task', task: task
      td
        = link_to 'edit', edit_task_path(task), class: 'btn-edit'
      td
        = link_to 'delete', task, class: 'btn-delete', method: :delete, data: { confirm: 'Delete tesk?' }

br
br
| Completed
table
  - @tasks.completed.each do |task|
    tr
      td
        = render 'task', task: task
      td
        = link_to 'edit', edit_task_path(task), class: 'btn-edit'
      td
        = link_to 'delete', task, class: 'btn-delete', method: :delete, data: { confirm: 'Delete tesk?' }

app/views/tasks/new.html.slim
h1
  = "Creating #{resource_task.title}"

= link_to  'Back', tasks_path

= render 'form', readonly: false

app/views/tasks/show.html.slim
h1 class="task-header"
  = resource_task.title

= link_to  'Back', tasks_path

= render 'form', readonly: true

app/views/users/new.html.slim
/ div class="login"
/   div class="container"
div class='form'

  h1
    | Sign up

  = form_for @user do |f|
    = f.text_field :first_name, placeholder: 'First name'
    = f.text_field :last_name, placeholder: 'Last name'
    = f.email_field :email, placeholder: 'Email'
    = f.password_field :password, placeholder: 'Password'
    = f.submit "Create account", class: 'btn-submit'